# Generated by Django 5.0.6 on 2025-02-28 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appeventor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datadesire',
            name='gender',
        ),
    ]
