# Generated by Django 5.0.6 on 2025-03-01 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeventor', '0002_remove_datadesire_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('username', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=16)),
                ('suggestion', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q_email', models.EmailField(max_length=254)),
                ('query', models.CharField(max_length=200)),
            ],
        ),
    ]
