# Generated by Django 5.0.6 on 2025-03-24 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appeventor', '0007_datadesire_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datadesire',
            name='user',
        ),
    ]
