# Generated by Django 5.0.6 on 2025-03-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeventor', '0008_remove_datadesire_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
