# Generated by Django 2.2 on 2025-03-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeventor', '0010_auto_20250325_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='fakepayment',
            name='eventname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
