# Generated by Django 2.2 on 2025-03-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeventor', '0011_fakepayment_eventname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12)),
                ('company', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=100)),
                ('typeofevent', models.CharField(max_length=100)),
                ('dateprimary', models.DateField()),
                ('datesecondary', models.DateField()),
                ('abouttheevent', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='fakepayment',
            name='eventname',
        ),
    ]
