pipeline { 
    agent { 
        label 'devops' 
    }
    options {
        timeout(time: 60, unit: 'SECONDS')
    }
    environment {
        IMAGE_NAME = "event-app"
        DOCKER_REPO = "your-dockerhub-username"  // Replace with your DockerHub username
    }
    stages {
        stage("Clone Code") {
            steps {
                echo "Cloning the code"
                git branch: 'main', url: 'https://github.com/kailash-Prajapati/Event.git'
            }
        }
        stage("Build") {
            steps {
                echo "Building the Docker image"
                sh "docker build -t ${IMAGE_NAME}:${BUILD_NUMBER} ."
            }
        }
        stage("Push to Docker Hub") {
            steps {
                echo "Pushing the image to Docker Hub"
                withCredentials([usernamePassword(credentialsId: "dockerHub", passwordVariable: "dockerHubPass", usernameVariable: "dockerHubUser")]) {
                    sh "docker tag event-app ${env.dockerHubUser}/event-app:latest"
                    sh "docker login -u ${env.dockerHubUser} -p ${env.dockerHubPass}"
                    sh "docker push ${env.dockerHubUser}/event-app:latest"
                }
            }
        }
        stage("Deploy") {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: "dockerHub", usernameVariable: "docker_user", passwordVariable: "docker_pass")]) {
                        sh """
                            docker login -u ${env.docker_user} -p ${env.docker_pass}
                            docker pull ${env.docker_user}/${IMAGE_NAME}:${BUILD_NUMBER}
                            docker run -dit --name python -p 8000:8000 ${env.docker_user}/${IMAGE_NAME}:${BUILD_NUMBER}
                        """
                    }
                }
            }
        }
    }
}
